import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";

const roboto = Roboto_Slab({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="font-system bg-black-primary">
        <div id="stars"></div>
        <div
          id="stars2"
          className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"
        ></div>
        <div id="stars3"></div>
        {children}
      </body>
    </html>
  );
}
