import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  weight: ["400"], // โหลดเท่าที่ใช้จริง
  display: "swap", // กัน FOIT
  preload: true, // ค่า default แต่ใส่ชัดเจน
  fallback: ["system-ui", "serif"],
  variable: "--font-roboto-slab", // เอาไว้ใช้กับ Tailwind
});
export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
  metadataBase: new URL("https://next-learn-dashboard.vercel.sh"),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={robotoSlab.variable}>
      <body className="font-system bg-black-primary">
        <div id="stars"></div>
        <div
          id="stars2"
          className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"
        ></div>
        <div id="stars3"></div>
        {children}
      </body>
    </html>
  );
}
